[2025-01-11T14:26:39.612+0000] {processor.py:186} INFO - Started process (PID=75) to work on /opt/airflow/dags/test.py
[2025-01-11T14:26:39.614+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-11T14:26:39.618+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:26:39.618+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-11T14:26:40.090+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:26:40.086+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-11T14:26:40.097+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-11T14:26:40.154+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:26:40.153+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-11T14:26:40.188+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:26:40.187+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-11T14:26:40.239+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.637 seconds
[2025-01-11T14:27:11.082+0000] {processor.py:186} INFO - Started process (PID=92) to work on /opt/airflow/dags/test.py
[2025-01-11T14:27:11.082+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-11T14:27:11.085+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:27:11.084+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-11T14:27:11.254+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:27:11.254+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-11T14:27:11.256+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-11T14:27:11.275+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:27:11.275+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-11T14:27:11.296+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:27:11.296+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-11T14:27:11.475+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.398 seconds
[2025-01-11T14:27:41.585+0000] {processor.py:186} INFO - Started process (PID=102) to work on /opt/airflow/dags/test.py
[2025-01-11T14:27:41.586+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-11T14:27:41.588+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:27:41.588+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-11T14:27:41.742+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:27:41.741+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-11T14:27:41.745+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-11T14:27:41.770+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:27:41.769+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-11T14:27:41.904+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:27:41.904+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-11T14:27:41.923+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.342 seconds
[2025-01-11T14:28:12.171+0000] {processor.py:186} INFO - Started process (PID=113) to work on /opt/airflow/dags/test.py
[2025-01-11T14:28:12.172+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-11T14:28:12.174+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:28:12.173+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-11T14:28:12.306+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:28:12.305+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-11T14:28:12.308+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-11T14:28:12.439+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:28:12.439+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-11T14:28:12.448+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:28:12.448+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-11T14:28:12.481+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.314 seconds
[2025-01-11T14:28:42.796+0000] {processor.py:186} INFO - Started process (PID=125) to work on /opt/airflow/dags/test.py
[2025-01-11T14:28:42.797+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-11T14:28:42.799+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:28:42.799+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-11T14:28:42.940+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:28:42.939+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-11T14:28:42.942+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-11T14:28:43.062+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:28:43.062+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-11T14:28:43.071+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:28:43.070+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-11T14:28:43.089+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.298 seconds
[2025-01-11T14:29:13.270+0000] {processor.py:186} INFO - Started process (PID=136) to work on /opt/airflow/dags/test.py
[2025-01-11T14:29:13.272+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-11T14:29:13.274+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:29:13.274+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-11T14:29:13.560+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:29:13.560+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-11T14:29:13.563+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-11T14:29:13.581+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:29:13.580+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-11T14:29:13.590+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:29:13.589+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-11T14:29:13.621+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.355 seconds
[2025-01-11T14:29:44.406+0000] {processor.py:186} INFO - Started process (PID=147) to work on /opt/airflow/dags/test.py
[2025-01-11T14:29:44.407+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-11T14:29:44.411+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:29:44.410+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-11T14:29:44.752+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:29:44.752+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-11T14:29:44.755+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-11T14:29:44.777+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:29:44.776+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-11T14:29:44.788+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:29:44.788+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-11T14:29:44.826+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.424 seconds
[2025-01-11T14:30:14.921+0000] {processor.py:186} INFO - Started process (PID=158) to work on /opt/airflow/dags/test.py
[2025-01-11T14:30:14.922+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-11T14:30:14.927+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:30:14.926+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-11T14:30:15.109+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:30:15.107+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-11T14:30:15.113+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-11T14:30:15.140+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:30:15.139+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-11T14:30:15.154+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:30:15.154+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-11T14:30:15.196+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.281 seconds
[2025-01-11T14:30:45.476+0000] {processor.py:186} INFO - Started process (PID=169) to work on /opt/airflow/dags/test.py
[2025-01-11T14:30:45.477+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-11T14:30:45.479+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:30:45.479+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-11T14:30:45.658+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:30:45.656+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-11T14:30:45.660+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-11T14:30:45.687+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:30:45.687+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-11T14:30:45.701+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:30:45.700+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-11T14:30:45.750+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.281 seconds
[2025-01-11T14:31:15.891+0000] {processor.py:186} INFO - Started process (PID=180) to work on /opt/airflow/dags/test.py
[2025-01-11T14:31:15.893+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-11T14:31:15.896+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:31:15.895+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-11T14:31:16.071+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:31:16.070+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-11T14:31:16.075+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-11T14:31:16.100+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:31:16.100+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-11T14:31:16.113+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:31:16.113+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-11T14:31:16.151+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.266 seconds
[2025-01-11T14:31:46.467+0000] {processor.py:186} INFO - Started process (PID=191) to work on /opt/airflow/dags/test.py
[2025-01-11T14:31:46.469+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-11T14:31:46.472+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:31:46.471+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-11T14:31:46.719+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:31:46.718+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-11T14:31:46.723+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-11T14:31:46.765+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:31:46.764+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-11T14:31:46.786+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:31:46.786+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-11T14:31:46.821+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.363 seconds
[2025-01-11T14:32:17.495+0000] {processor.py:186} INFO - Started process (PID=202) to work on /opt/airflow/dags/test.py
[2025-01-11T14:32:17.496+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-11T14:32:17.498+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:32:17.498+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-11T14:32:17.656+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:32:17.655+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-11T14:32:17.659+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-11T14:32:17.681+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:32:17.681+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-11T14:32:17.693+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:32:17.693+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-11T14:32:17.730+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.241 seconds
[2025-01-11T14:32:47.859+0000] {processor.py:186} INFO - Started process (PID=213) to work on /opt/airflow/dags/test.py
[2025-01-11T14:32:47.860+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-11T14:32:47.863+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:32:47.862+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-11T14:32:48.046+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:32:48.045+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-11T14:32:48.049+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-11T14:32:48.075+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:32:48.075+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-11T14:32:48.089+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:32:48.089+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-11T14:32:48.130+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.277 seconds
[2025-01-11T14:33:18.931+0000] {processor.py:186} INFO - Started process (PID=224) to work on /opt/airflow/dags/test.py
[2025-01-11T14:33:18.933+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-11T14:33:18.936+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:33:18.936+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-11T14:33:19.118+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:33:19.117+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-11T14:33:19.122+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-11T14:33:19.147+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:33:19.147+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-11T14:33:19.160+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:33:19.160+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-11T14:33:19.187+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.261 seconds
[2025-01-11T14:33:49.368+0000] {processor.py:186} INFO - Started process (PID=235) to work on /opt/airflow/dags/test.py
[2025-01-11T14:33:49.369+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-11T14:33:49.370+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:33:49.370+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-11T14:33:49.501+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:33:49.500+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-11T14:33:49.503+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-11T14:33:49.521+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:33:49.521+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-11T14:33:49.531+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:33:49.531+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-11T14:33:49.548+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.184 seconds
[2025-01-11T14:34:20.155+0000] {processor.py:186} INFO - Started process (PID=246) to work on /opt/airflow/dags/test.py
[2025-01-11T14:34:20.157+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-11T14:34:20.159+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:34:20.159+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-11T14:34:20.322+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:34:20.321+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-11T14:34:20.325+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-11T14:34:20.348+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:34:20.347+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-11T14:34:20.359+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:34:20.359+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-11T14:34:20.384+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.240 seconds
[2025-01-11T14:34:51.208+0000] {processor.py:186} INFO - Started process (PID=257) to work on /opt/airflow/dags/test.py
[2025-01-11T14:34:51.214+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-11T14:34:51.218+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:34:51.218+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-11T14:34:51.346+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:34:51.346+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-11T14:34:51.349+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-11T14:34:51.366+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:34:51.366+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-11T14:34:51.376+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:34:51.376+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-11T14:34:51.407+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.203 seconds
[2025-01-11T14:35:21.884+0000] {processor.py:186} INFO - Started process (PID=268) to work on /opt/airflow/dags/test.py
[2025-01-11T14:35:21.885+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-11T14:35:21.887+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:35:21.886+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-11T14:35:22.021+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:35:22.020+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-11T14:35:22.023+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-11T14:35:22.042+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:35:22.042+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-11T14:35:22.054+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:35:22.054+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-11T14:35:22.073+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.195 seconds
[2025-01-11T14:35:52.285+0000] {processor.py:186} INFO - Started process (PID=279) to work on /opt/airflow/dags/test.py
[2025-01-11T14:35:52.286+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-11T14:35:52.288+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:35:52.288+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-11T14:35:52.420+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:35:52.420+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-11T14:35:52.422+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-11T14:35:52.442+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:35:52.441+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-11T14:35:52.452+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:35:52.452+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-11T14:35:52.479+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.198 seconds
[2025-01-11T14:36:23.250+0000] {processor.py:186} INFO - Started process (PID=290) to work on /opt/airflow/dags/test.py
[2025-01-11T14:36:23.252+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-11T14:36:23.254+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:36:23.254+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-11T14:36:23.435+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:36:23.434+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-11T14:36:23.438+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-11T14:36:23.462+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:36:23.462+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-11T14:36:23.475+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:36:23.475+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-11T14:36:23.506+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.261 seconds
[2025-01-11T14:47:12.581+0000] {processor.py:186} INFO - Started process (PID=75) to work on /opt/airflow/dags/test.py
[2025-01-11T14:47:12.585+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-11T14:47:12.590+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:47:12.589+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-11T14:47:13.251+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:47:13.247+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-11T14:47:13.259+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-11T14:47:13.316+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:47:13.316+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-11T14:47:13.355+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:47:13.354+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-11T14:47:13.411+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.840 seconds
[2025-01-11T14:47:43.664+0000] {processor.py:186} INFO - Started process (PID=85) to work on /opt/airflow/dags/test.py
[2025-01-11T14:47:43.665+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-11T14:47:43.667+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:47:43.666+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-11T14:47:43.814+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:47:43.813+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-11T14:47:43.816+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-11T14:47:43.842+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:47:43.842+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-11T14:47:43.855+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:47:43.855+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-11T14:47:43.983+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.323 seconds
[2025-01-11T14:48:14.134+0000] {processor.py:186} INFO - Started process (PID=96) to work on /opt/airflow/dags/test.py
[2025-01-11T14:48:14.135+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-11T14:48:14.137+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:48:14.136+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-11T14:48:14.275+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:48:14.274+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-11T14:48:14.277+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-11T14:48:14.299+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:48:14.299+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-11T14:48:14.423+0000] {logging_mixin.py:190} INFO - [2025-01-11T14:48:14.423+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-11T14:48:14.439+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.309 seconds
