[2025-01-21T17:30:32.245+0000] {processor.py:186} INFO - Started process (PID=76) to work on /opt/airflow/dags/test.py
[2025-01-21T17:30:32.248+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T17:30:32.253+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:30:32.252+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T17:30:32.626+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:30:32.622+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T17:30:32.633+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T17:30:32.688+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:30:32.687+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T17:30:32.718+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:30:32.718+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T17:30:32.764+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.532 seconds
[2025-01-21T17:31:03.436+0000] {processor.py:186} INFO - Started process (PID=87) to work on /opt/airflow/dags/test.py
[2025-01-21T17:31:03.437+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T17:31:03.439+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:31:03.439+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T17:31:03.605+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:31:03.604+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T17:31:03.608+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T17:31:03.639+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:31:03.638+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T17:31:03.660+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:31:03.660+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T17:31:03.701+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.270 seconds
[2025-01-21T17:31:33.766+0000] {processor.py:186} INFO - Started process (PID=97) to work on /opt/airflow/dags/test.py
[2025-01-21T17:31:33.767+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T17:31:33.769+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:31:33.769+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T17:31:33.910+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:31:33.909+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T17:31:33.912+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T17:31:33.934+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:31:33.934+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T17:31:34.064+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:31:34.063+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T17:31:34.099+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.339 seconds
[2025-01-21T17:32:04.307+0000] {processor.py:186} INFO - Started process (PID=108) to work on /opt/airflow/dags/test.py
[2025-01-21T17:32:04.308+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T17:32:04.310+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:32:04.310+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T17:32:04.583+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:32:04.582+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T17:32:04.587+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T17:32:04.622+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:32:04.622+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T17:32:04.783+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:32:04.783+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T17:32:04.808+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.507 seconds
[2025-01-21T17:32:35.654+0000] {processor.py:186} INFO - Started process (PID=125) to work on /opt/airflow/dags/test.py
[2025-01-21T17:32:35.655+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T17:32:35.657+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:32:35.657+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T17:32:35.824+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:32:35.823+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T17:32:35.826+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T17:32:35.969+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:32:35.969+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T17:32:35.979+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:32:35.979+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T17:32:36.008+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.359 seconds
[2025-01-21T17:33:06.146+0000] {processor.py:186} INFO - Started process (PID=136) to work on /opt/airflow/dags/test.py
[2025-01-21T17:33:06.147+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T17:33:06.149+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:33:06.149+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T17:33:06.433+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:33:06.432+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T17:33:06.436+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T17:33:06.455+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:33:06.454+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T17:33:06.467+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:33:06.466+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T17:33:06.488+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.346 seconds
[2025-01-21T17:33:36.915+0000] {processor.py:186} INFO - Started process (PID=146) to work on /opt/airflow/dags/test.py
[2025-01-21T17:33:36.916+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T17:33:36.918+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:33:36.918+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T17:33:37.176+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:33:37.175+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T17:33:37.178+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T17:33:37.195+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:33:37.195+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T17:33:37.205+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:33:37.205+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T17:33:37.238+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.327 seconds
[2025-01-21T17:34:07.346+0000] {processor.py:186} INFO - Started process (PID=157) to work on /opt/airflow/dags/test.py
[2025-01-21T17:34:07.348+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T17:34:07.350+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:34:07.350+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T17:34:07.545+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:34:07.544+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T17:34:07.547+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T17:34:07.572+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:34:07.572+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T17:34:07.587+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:34:07.587+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T17:34:07.616+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.276 seconds
[2025-01-21T17:34:38.296+0000] {processor.py:186} INFO - Started process (PID=168) to work on /opt/airflow/dags/test.py
[2025-01-21T17:34:38.297+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T17:34:38.300+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:34:38.299+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T17:34:38.492+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:34:38.491+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T17:34:38.495+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T17:34:38.518+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:34:38.517+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T17:34:38.529+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:34:38.529+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T17:34:38.567+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.278 seconds
[2025-01-21T17:35:08.898+0000] {processor.py:186} INFO - Started process (PID=179) to work on /opt/airflow/dags/test.py
[2025-01-21T17:35:08.899+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T17:35:08.903+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:35:08.902+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T17:35:09.088+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:35:09.087+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T17:35:09.090+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T17:35:09.117+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:35:09.117+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T17:35:09.129+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:35:09.129+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T17:35:09.152+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.260 seconds
[2025-01-21T17:35:39.463+0000] {processor.py:186} INFO - Started process (PID=190) to work on /opt/airflow/dags/test.py
[2025-01-21T17:35:39.464+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T17:35:39.466+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:35:39.465+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T17:35:39.603+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:35:39.602+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T17:35:39.605+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T17:35:39.629+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:35:39.629+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T17:35:39.640+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:35:39.640+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T17:35:39.673+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.216 seconds
[2025-01-21T17:36:09.731+0000] {processor.py:186} INFO - Started process (PID=201) to work on /opt/airflow/dags/test.py
[2025-01-21T17:36:09.731+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T17:36:09.733+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:36:09.733+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T17:36:09.868+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:36:09.867+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T17:36:09.870+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T17:36:09.891+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:36:09.891+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T17:36:09.902+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:36:09.901+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T17:36:09.922+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.196 seconds
[2025-01-21T17:36:40.152+0000] {processor.py:186} INFO - Started process (PID=212) to work on /opt/airflow/dags/test.py
[2025-01-21T17:36:40.153+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T17:36:40.155+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:36:40.155+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T17:36:40.305+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:36:40.303+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T17:36:40.308+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T17:36:40.332+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:36:40.332+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T17:36:40.346+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:36:40.345+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T17:36:40.369+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.223 seconds
[2025-01-21T17:37:10.420+0000] {processor.py:186} INFO - Started process (PID=223) to work on /opt/airflow/dags/test.py
[2025-01-21T17:37:10.421+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T17:37:10.424+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:37:10.423+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T17:37:10.569+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:37:10.568+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T17:37:10.571+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T17:37:10.593+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:37:10.593+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T17:37:10.604+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:37:10.604+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T17:37:10.625+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.210 seconds
[2025-01-21T17:37:40.760+0000] {processor.py:186} INFO - Started process (PID=234) to work on /opt/airflow/dags/test.py
[2025-01-21T17:37:40.761+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T17:37:40.763+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:37:40.763+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T17:37:40.912+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:37:40.912+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T17:37:40.915+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T17:37:40.936+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:37:40.936+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T17:37:40.948+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:37:40.947+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T17:37:40.978+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.224 seconds
[2025-01-21T17:38:11.140+0000] {processor.py:186} INFO - Started process (PID=245) to work on /opt/airflow/dags/test.py
[2025-01-21T17:38:11.142+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T17:38:11.144+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:38:11.144+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T17:38:11.283+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:38:11.282+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T17:38:11.285+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T17:38:11.307+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:38:11.307+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T17:38:11.318+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:38:11.318+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T17:38:11.356+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.222 seconds
[2025-01-21T17:38:41.575+0000] {processor.py:186} INFO - Started process (PID=256) to work on /opt/airflow/dags/test.py
[2025-01-21T17:38:41.577+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T17:38:41.581+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:38:41.580+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T17:38:41.755+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:38:41.754+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T17:38:41.758+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T17:38:41.788+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:38:41.787+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T17:38:41.803+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:38:41.803+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T17:38:41.840+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.272 seconds
[2025-01-21T17:39:12.477+0000] {processor.py:186} INFO - Started process (PID=267) to work on /opt/airflow/dags/test.py
[2025-01-21T17:39:12.479+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T17:39:12.481+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:39:12.481+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T17:39:12.672+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:39:12.671+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T17:39:12.675+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T17:39:12.700+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:39:12.700+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T17:39:12.718+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:39:12.717+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T17:39:12.749+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.279 seconds
[2025-01-21T17:39:42.936+0000] {processor.py:186} INFO - Started process (PID=278) to work on /opt/airflow/dags/test.py
[2025-01-21T17:39:42.937+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T17:39:42.939+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:39:42.939+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T17:39:43.072+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:39:43.072+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T17:39:43.074+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T17:39:43.096+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:39:43.095+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T17:39:43.108+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:39:43.108+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T17:39:43.125+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.195 seconds
[2025-01-21T17:40:13.367+0000] {processor.py:186} INFO - Started process (PID=289) to work on /opt/airflow/dags/test.py
[2025-01-21T17:40:13.368+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T17:40:13.371+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:40:13.371+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T17:40:13.530+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:40:13.529+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T17:40:13.532+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T17:40:13.553+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:40:13.553+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T17:40:13.566+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:40:13.566+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T17:40:13.588+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.225 seconds
[2025-01-21T17:40:43.957+0000] {processor.py:186} INFO - Started process (PID=300) to work on /opt/airflow/dags/test.py
[2025-01-21T17:40:43.958+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T17:40:43.961+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:40:43.960+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T17:40:44.101+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:40:44.100+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T17:40:44.104+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T17:40:44.125+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:40:44.124+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T17:40:44.137+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:40:44.137+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T17:40:44.170+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.219 seconds
[2025-01-21T17:41:14.271+0000] {processor.py:186} INFO - Started process (PID=311) to work on /opt/airflow/dags/test.py
[2025-01-21T17:41:14.272+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T17:41:14.274+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:41:14.273+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T17:41:14.402+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:41:14.401+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T17:41:14.404+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T17:41:14.425+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:41:14.425+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T17:41:14.437+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:41:14.437+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T17:41:14.460+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.193 seconds
[2025-01-21T17:41:44.801+0000] {processor.py:186} INFO - Started process (PID=322) to work on /opt/airflow/dags/test.py
[2025-01-21T17:41:44.803+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T17:41:44.807+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:41:44.807+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T17:41:44.998+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:41:44.997+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T17:41:45.001+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T17:41:45.029+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:41:45.029+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T17:41:45.045+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:41:45.045+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T17:41:45.073+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.278 seconds
[2025-01-21T17:42:15.737+0000] {processor.py:186} INFO - Started process (PID=333) to work on /opt/airflow/dags/test.py
[2025-01-21T17:42:15.739+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T17:42:15.742+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:42:15.742+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T17:42:15.911+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:42:15.910+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T17:42:15.914+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T17:42:15.940+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:42:15.939+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T17:42:15.955+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:42:15.955+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T17:42:15.982+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.252 seconds
[2025-01-21T17:42:46.320+0000] {processor.py:186} INFO - Started process (PID=344) to work on /opt/airflow/dags/test.py
[2025-01-21T17:42:46.321+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T17:42:46.325+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:42:46.324+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T17:42:46.487+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:42:46.486+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T17:42:46.489+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T17:42:46.512+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:42:46.512+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T17:42:46.525+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:42:46.525+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T17:42:46.553+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.238 seconds
[2025-01-21T17:43:16.722+0000] {processor.py:186} INFO - Started process (PID=355) to work on /opt/airflow/dags/test.py
[2025-01-21T17:43:16.723+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T17:43:16.725+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:43:16.725+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T17:43:16.877+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:43:16.877+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T17:43:16.880+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T17:43:16.903+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:43:16.903+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T17:43:16.916+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:43:16.915+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T17:43:16.950+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.232 seconds
[2025-01-21T17:43:47.208+0000] {processor.py:186} INFO - Started process (PID=366) to work on /opt/airflow/dags/test.py
[2025-01-21T17:43:47.210+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T17:43:47.212+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:43:47.212+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T17:43:47.352+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:43:47.352+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T17:43:47.354+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T17:43:47.373+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:43:47.373+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T17:43:47.385+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:43:47.385+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T17:43:47.419+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.215 seconds
[2025-01-21T17:44:17.728+0000] {processor.py:186} INFO - Started process (PID=377) to work on /opt/airflow/dags/test.py
[2025-01-21T17:44:17.729+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T17:44:17.731+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:44:17.731+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T17:44:17.861+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:44:17.861+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T17:44:17.864+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T17:44:17.882+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:44:17.882+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T17:44:17.894+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:44:17.894+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T17:44:17.927+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.204 seconds
[2025-01-21T17:44:48.100+0000] {processor.py:186} INFO - Started process (PID=389) to work on /opt/airflow/dags/test.py
[2025-01-21T17:44:48.101+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T17:44:48.103+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:44:48.103+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T17:44:48.277+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:44:48.276+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T17:44:48.280+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T17:44:48.302+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:44:48.301+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T17:44:48.315+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:44:48.314+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T17:44:48.349+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.255 seconds
[2025-01-21T17:45:18.606+0000] {processor.py:186} INFO - Started process (PID=400) to work on /opt/airflow/dags/test.py
[2025-01-21T17:45:18.607+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T17:45:18.610+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:45:18.610+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T17:45:18.754+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:45:18.754+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T17:45:18.756+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T17:45:18.776+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:45:18.776+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T17:45:18.787+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:45:18.787+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T17:45:18.805+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.204 seconds
[2025-01-21T17:45:49.079+0000] {processor.py:186} INFO - Started process (PID=411) to work on /opt/airflow/dags/test.py
[2025-01-21T17:45:49.081+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T17:45:49.084+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:45:49.083+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T17:45:49.261+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:45:49.260+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T17:45:49.264+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T17:45:49.288+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:45:49.288+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T17:45:49.303+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:45:49.302+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T17:45:49.327+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.255 seconds
[2025-01-21T17:46:19.641+0000] {processor.py:186} INFO - Started process (PID=423) to work on /opt/airflow/dags/test.py
[2025-01-21T17:46:19.643+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T17:46:19.646+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:46:19.646+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T17:46:19.865+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:46:19.860+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T17:46:19.871+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T17:46:19.904+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:46:19.904+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T17:46:19.920+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:46:19.919+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T17:46:19.947+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.313 seconds
[2025-01-21T17:46:50.557+0000] {processor.py:186} INFO - Started process (PID=434) to work on /opt/airflow/dags/test.py
[2025-01-21T17:46:50.559+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T17:46:50.562+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:46:50.562+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T17:46:50.746+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:46:50.744+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T17:46:50.749+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T17:46:50.783+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:46:50.783+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T17:46:50.799+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:46:50.799+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T17:46:50.838+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.289 seconds
[2025-01-21T17:47:21.096+0000] {processor.py:186} INFO - Started process (PID=445) to work on /opt/airflow/dags/test.py
[2025-01-21T17:47:21.097+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T17:47:21.100+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:47:21.099+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T17:47:21.287+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:47:21.287+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T17:47:21.290+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T17:47:21.320+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:47:21.319+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T17:47:21.339+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:47:21.339+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T17:47:21.382+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.292 seconds
[2025-01-21T17:47:52.042+0000] {processor.py:186} INFO - Started process (PID=456) to work on /opt/airflow/dags/test.py
[2025-01-21T17:47:52.044+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T17:47:52.047+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:47:52.046+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T17:47:52.288+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:47:52.287+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T17:47:52.290+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T17:47:52.325+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:47:52.325+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T17:47:52.343+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:47:52.342+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T17:47:52.387+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.352 seconds
[2025-01-21T17:48:22.591+0000] {processor.py:186} INFO - Started process (PID=467) to work on /opt/airflow/dags/test.py
[2025-01-21T17:48:22.593+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T17:48:22.597+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:48:22.596+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T17:48:22.773+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:48:22.772+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T17:48:22.777+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T17:48:22.803+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:48:22.803+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T17:48:22.817+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:48:22.817+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T17:48:22.854+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.270 seconds
[2025-01-21T17:48:53.527+0000] {processor.py:186} INFO - Started process (PID=478) to work on /opt/airflow/dags/test.py
[2025-01-21T17:48:53.528+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T17:48:53.531+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:48:53.530+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T17:48:53.703+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:48:53.701+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T17:48:53.708+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T17:48:53.731+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:48:53.730+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T17:48:53.743+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:48:53.743+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T17:48:53.765+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.244 seconds
[2025-01-21T17:49:23.973+0000] {processor.py:186} INFO - Started process (PID=489) to work on /opt/airflow/dags/test.py
[2025-01-21T17:49:23.975+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T17:49:23.981+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:49:23.980+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T17:49:24.184+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:49:24.183+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T17:49:24.186+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T17:49:24.218+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:49:24.217+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T17:49:24.233+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:49:24.232+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T17:49:24.278+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.311 seconds
[2025-01-21T17:49:54.946+0000] {processor.py:186} INFO - Started process (PID=500) to work on /opt/airflow/dags/test.py
[2025-01-21T17:49:54.947+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T17:49:54.950+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:49:54.949+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T17:49:55.131+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:49:55.130+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T17:49:55.148+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T17:49:55.175+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:49:55.174+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T17:49:55.190+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:49:55.190+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T17:49:55.221+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.285 seconds
[2025-01-21T17:50:25.404+0000] {processor.py:186} INFO - Started process (PID=511) to work on /opt/airflow/dags/test.py
[2025-01-21T17:50:25.405+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T17:50:25.409+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:50:25.408+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T17:50:25.595+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:50:25.592+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T17:50:25.598+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T17:50:25.630+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:50:25.630+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T17:50:25.645+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:50:25.645+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T17:50:25.681+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.283 seconds
[2025-01-21T17:50:56.234+0000] {processor.py:186} INFO - Started process (PID=522) to work on /opt/airflow/dags/test.py
[2025-01-21T17:50:56.235+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T17:50:56.238+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:50:56.238+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T17:50:56.420+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:50:56.419+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T17:50:56.424+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T17:50:56.455+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:50:56.454+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T17:50:56.471+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:50:56.471+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T17:50:56.509+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.281 seconds
[2025-01-21T17:51:26.824+0000] {processor.py:186} INFO - Started process (PID=533) to work on /opt/airflow/dags/test.py
[2025-01-21T17:51:26.825+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T17:51:26.828+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:51:26.828+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T17:51:26.975+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:51:26.974+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T17:51:26.977+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T17:51:27.001+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:51:27.001+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T17:51:27.013+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:51:27.013+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T17:51:27.051+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.233 seconds
[2025-01-21T17:51:57.677+0000] {processor.py:186} INFO - Started process (PID=544) to work on /opt/airflow/dags/test.py
[2025-01-21T17:51:57.678+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T17:51:57.681+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:51:57.681+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T17:51:57.873+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:51:57.872+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T17:51:57.877+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T17:51:57.903+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:51:57.903+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T17:51:57.917+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:51:57.917+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T17:51:57.959+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.289 seconds
[2025-01-21T17:52:28.044+0000] {processor.py:186} INFO - Started process (PID=555) to work on /opt/airflow/dags/test.py
[2025-01-21T17:52:28.046+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T17:52:28.048+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:52:28.048+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T17:52:28.213+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:52:28.212+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T17:52:28.215+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T17:52:28.238+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:52:28.238+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T17:52:28.251+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:52:28.251+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T17:52:28.287+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.249 seconds
[2025-01-21T17:52:58.379+0000] {processor.py:186} INFO - Started process (PID=566) to work on /opt/airflow/dags/test.py
[2025-01-21T17:52:58.380+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T17:52:58.382+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:52:58.382+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T17:52:58.541+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:52:58.540+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T17:52:58.543+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T17:52:58.565+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:52:58.565+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T17:52:58.579+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:52:58.578+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T17:52:58.599+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.227 seconds
[2025-01-21T17:53:28.723+0000] {processor.py:186} INFO - Started process (PID=577) to work on /opt/airflow/dags/test.py
[2025-01-21T17:53:28.724+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T17:53:28.726+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:53:28.726+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T17:53:28.856+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:53:28.855+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T17:53:28.858+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T17:53:28.878+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:53:28.878+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T17:53:28.890+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:53:28.889+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T17:53:28.909+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.191 seconds
[2025-01-21T17:53:58.973+0000] {processor.py:186} INFO - Started process (PID=588) to work on /opt/airflow/dags/test.py
[2025-01-21T17:53:58.973+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T17:53:58.975+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:53:58.975+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T17:53:59.102+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:53:59.101+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T17:53:59.104+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T17:53:59.122+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:53:59.122+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T17:53:59.133+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:53:59.132+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T17:53:59.163+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.195 seconds
[2025-01-21T17:54:29.760+0000] {processor.py:186} INFO - Started process (PID=599) to work on /opt/airflow/dags/test.py
[2025-01-21T17:54:29.761+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T17:54:29.763+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:54:29.763+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T17:54:29.907+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:54:29.907+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T17:54:29.910+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T17:54:29.931+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:54:29.930+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T17:54:29.941+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:54:29.941+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T17:54:29.971+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.216 seconds
[2025-01-21T17:55:00.338+0000] {processor.py:186} INFO - Started process (PID=610) to work on /opt/airflow/dags/test.py
[2025-01-21T17:55:00.340+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T17:55:00.343+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:55:00.342+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T17:55:00.527+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:55:00.526+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T17:55:00.530+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T17:55:00.554+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:55:00.553+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T17:55:00.568+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:55:00.567+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T17:55:00.603+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.272 seconds
[2025-01-21T17:55:30.990+0000] {processor.py:186} INFO - Started process (PID=621) to work on /opt/airflow/dags/test.py
[2025-01-21T17:55:30.991+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T17:55:30.993+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:55:30.993+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T17:55:31.172+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:55:31.171+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T17:55:31.174+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T17:55:31.198+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:55:31.198+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T17:55:31.214+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:55:31.214+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T17:55:31.239+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.255 seconds
[2025-01-21T17:56:01.716+0000] {processor.py:186} INFO - Started process (PID=632) to work on /opt/airflow/dags/test.py
[2025-01-21T17:56:01.718+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T17:56:01.720+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:56:01.720+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T17:56:01.863+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:56:01.862+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T17:56:01.865+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T17:56:01.884+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:56:01.884+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T17:56:01.894+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:56:01.894+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T17:56:01.912+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.201 seconds
[2025-01-21T17:56:32.371+0000] {processor.py:186} INFO - Started process (PID=643) to work on /opt/airflow/dags/test.py
[2025-01-21T17:56:32.372+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T17:56:32.375+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:56:32.374+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T17:56:32.517+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:56:32.516+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T17:56:32.519+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T17:56:32.540+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:56:32.540+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T17:56:32.551+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:56:32.551+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T17:56:32.571+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.206 seconds
[2025-01-21T17:57:02.693+0000] {processor.py:186} INFO - Started process (PID=654) to work on /opt/airflow/dags/test.py
[2025-01-21T17:57:02.694+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T17:57:02.696+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:57:02.696+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T17:57:02.828+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:57:02.827+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T17:57:02.831+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T17:57:02.851+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:57:02.850+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T17:57:02.862+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:57:02.862+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T17:57:02.899+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.211 seconds
[2025-01-21T17:57:33.041+0000] {processor.py:186} INFO - Started process (PID=665) to work on /opt/airflow/dags/test.py
[2025-01-21T17:57:33.042+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T17:57:33.045+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:57:33.044+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T17:57:33.242+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:57:33.241+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T17:57:33.244+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T17:57:33.271+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:57:33.271+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T17:57:33.284+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:57:33.284+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T17:57:33.325+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.290 seconds
[2025-01-21T17:58:03.398+0000] {processor.py:186} INFO - Started process (PID=676) to work on /opt/airflow/dags/test.py
[2025-01-21T17:58:03.400+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T17:58:03.402+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:58:03.402+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T17:58:03.584+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:58:03.583+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T17:58:03.587+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T17:58:03.610+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:58:03.609+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T17:58:03.624+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:58:03.624+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T17:58:03.658+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.265 seconds
[2025-01-21T17:58:34.196+0000] {processor.py:186} INFO - Started process (PID=687) to work on /opt/airflow/dags/test.py
[2025-01-21T17:58:34.197+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T17:58:34.200+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:58:34.200+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T17:58:34.413+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:58:34.413+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T17:58:34.415+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T17:58:34.435+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:58:34.435+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T17:58:34.447+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:58:34.447+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T17:58:34.481+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.290 seconds
[2025-01-21T17:59:04.542+0000] {processor.py:186} INFO - Started process (PID=698) to work on /opt/airflow/dags/test.py
[2025-01-21T17:59:04.543+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T17:59:04.545+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:59:04.545+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T17:59:04.700+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:59:04.699+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T17:59:04.703+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T17:59:04.724+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:59:04.724+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T17:59:04.736+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:59:04.736+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T17:59:04.762+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.226 seconds
[2025-01-21T17:59:35.240+0000] {processor.py:186} INFO - Started process (PID=709) to work on /opt/airflow/dags/test.py
[2025-01-21T17:59:35.241+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T17:59:35.245+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:59:35.245+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T17:59:35.416+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:59:35.415+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T17:59:35.419+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T17:59:35.442+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:59:35.442+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T17:59:35.455+0000] {logging_mixin.py:190} INFO - [2025-01-21T17:59:35.454+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T17:59:35.481+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.247 seconds
[2025-01-21T18:00:05.606+0000] {processor.py:186} INFO - Started process (PID=720) to work on /opt/airflow/dags/test.py
[2025-01-21T18:00:05.608+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T18:00:05.612+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:00:05.611+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T18:00:05.787+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:00:05.786+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T18:00:05.790+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T18:00:05.814+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:00:05.814+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T18:00:05.827+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:00:05.827+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T18:00:05.853+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.253 seconds
[2025-01-21T18:00:36.432+0000] {processor.py:186} INFO - Started process (PID=731) to work on /opt/airflow/dags/test.py
[2025-01-21T18:00:36.433+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T18:00:36.436+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:00:36.436+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T18:00:36.675+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:00:36.673+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T18:00:36.683+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T18:00:36.733+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:00:36.733+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T18:00:36.751+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:00:36.751+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T18:00:36.785+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.360 seconds
[2025-01-21T18:01:07.107+0000] {processor.py:186} INFO - Started process (PID=748) to work on /opt/airflow/dags/test.py
[2025-01-21T18:01:07.109+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T18:01:07.114+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:01:07.113+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T18:01:07.312+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:01:07.310+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T18:01:07.315+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T18:01:07.344+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:01:07.344+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T18:01:07.361+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:01:07.360+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T18:01:07.418+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.321 seconds
[2025-01-21T18:01:37.812+0000] {processor.py:186} INFO - Started process (PID=760) to work on /opt/airflow/dags/test.py
[2025-01-21T18:01:37.813+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T18:01:37.816+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:01:37.816+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T18:01:37.998+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:01:37.997+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T18:01:38.001+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T18:01:38.025+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:01:38.024+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T18:01:38.053+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:01:38.052+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T18:01:38.080+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.275 seconds
[2025-01-21T18:02:08.619+0000] {processor.py:186} INFO - Started process (PID=771) to work on /opt/airflow/dags/test.py
[2025-01-21T18:02:08.621+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T18:02:08.623+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:02:08.623+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T18:02:08.804+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:02:08.803+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T18:02:08.807+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T18:02:08.834+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:02:08.833+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T18:02:08.847+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:02:08.847+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T18:02:08.884+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.270 seconds
[2025-01-21T18:02:39.056+0000] {processor.py:186} INFO - Started process (PID=782) to work on /opt/airflow/dags/test.py
[2025-01-21T18:02:39.057+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T18:02:39.060+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:02:39.060+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T18:02:39.293+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:02:39.291+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T18:02:39.296+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T18:02:39.328+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:02:39.327+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T18:02:39.346+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:02:39.346+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T18:02:39.387+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.339 seconds
[2025-01-21T18:03:09.689+0000] {processor.py:186} INFO - Started process (PID=792) to work on /opt/airflow/dags/test.py
[2025-01-21T18:03:09.690+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T18:03:09.692+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:03:09.691+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T18:03:09.882+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:03:09.881+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T18:03:09.884+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T18:03:09.912+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:03:09.911+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T18:03:09.929+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:03:09.929+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T18:03:09.953+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.269 seconds
[2025-01-21T18:03:40.398+0000] {processor.py:186} INFO - Started process (PID=803) to work on /opt/airflow/dags/test.py
[2025-01-21T18:03:40.399+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T18:03:40.401+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:03:40.401+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T18:03:40.587+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:03:40.586+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T18:03:40.593+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T18:03:40.627+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:03:40.627+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T18:03:40.651+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:03:40.651+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T18:03:40.701+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.310 seconds
[2025-01-21T18:04:11.449+0000] {processor.py:186} INFO - Started process (PID=814) to work on /opt/airflow/dags/test.py
[2025-01-21T18:04:11.450+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T18:04:11.452+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:04:11.452+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T18:04:11.622+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:04:11.621+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T18:04:11.625+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T18:04:11.648+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:04:11.647+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T18:04:11.665+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:04:11.664+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T18:04:11.707+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.264 seconds
[2025-01-21T18:04:41.823+0000] {processor.py:186} INFO - Started process (PID=824) to work on /opt/airflow/dags/test.py
[2025-01-21T18:04:41.825+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T18:04:41.827+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:04:41.827+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T18:04:42.086+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:04:42.085+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T18:04:42.088+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T18:04:42.116+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:04:42.116+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T18:04:42.129+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:04:42.129+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T18:04:42.167+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.350 seconds
[2025-01-21T18:05:12.421+0000] {processor.py:186} INFO - Started process (PID=835) to work on /opt/airflow/dags/test.py
[2025-01-21T18:05:12.422+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T18:05:12.425+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:05:12.424+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T18:05:12.604+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:05:12.603+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T18:05:12.607+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T18:05:12.631+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:05:12.630+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T18:05:12.643+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:05:12.643+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T18:05:12.673+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.258 seconds
[2025-01-21T18:05:43.085+0000] {processor.py:186} INFO - Started process (PID=846) to work on /opt/airflow/dags/test.py
[2025-01-21T18:05:43.086+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T18:05:43.091+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:05:43.091+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T18:05:43.253+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:05:43.252+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T18:05:43.257+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T18:05:43.286+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:05:43.286+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T18:05:43.303+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:05:43.302+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T18:05:43.328+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.248 seconds
[2025-01-21T18:06:13.488+0000] {processor.py:186} INFO - Started process (PID=858) to work on /opt/airflow/dags/test.py
[2025-01-21T18:06:13.489+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T18:06:13.491+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:06:13.491+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T18:06:13.662+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:06:13.661+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T18:06:13.665+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T18:06:13.694+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:06:13.694+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T18:06:13.710+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:06:13.710+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T18:06:13.745+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.263 seconds
[2025-01-21T18:06:44.044+0000] {processor.py:186} INFO - Started process (PID=869) to work on /opt/airflow/dags/test.py
[2025-01-21T18:06:44.045+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T18:06:44.048+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:06:44.047+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T18:06:44.245+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:06:44.244+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T18:06:44.247+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T18:06:44.275+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:06:44.275+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T18:06:44.293+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:06:44.292+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T18:06:44.316+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.279 seconds
[2025-01-21T18:07:14.439+0000] {processor.py:186} INFO - Started process (PID=880) to work on /opt/airflow/dags/test.py
[2025-01-21T18:07:14.441+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T18:07:14.443+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:07:14.442+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T18:07:14.607+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:07:14.607+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T18:07:14.610+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T18:07:14.631+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:07:14.631+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T18:07:14.643+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:07:14.643+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T18:07:14.667+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.233 seconds
[2025-01-21T18:07:45.027+0000] {processor.py:186} INFO - Started process (PID=891) to work on /opt/airflow/dags/test.py
[2025-01-21T18:07:45.030+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T18:07:45.034+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:07:45.033+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T18:07:45.391+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:07:45.389+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T18:07:45.401+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T18:07:45.454+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:07:45.454+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T18:07:45.484+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:07:45.484+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T18:07:45.548+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.540 seconds
[2025-01-21T18:08:16.025+0000] {processor.py:186} INFO - Started process (PID=901) to work on /opt/airflow/dags/test.py
[2025-01-21T18:08:16.028+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T18:08:16.033+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:08:16.032+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T18:08:16.469+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:08:16.467+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T18:08:16.473+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T18:08:16.532+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:08:16.531+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T18:08:16.567+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:08:16.566+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T18:08:16.611+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.599 seconds
[2025-01-21T18:08:47.226+0000] {processor.py:186} INFO - Started process (PID=912) to work on /opt/airflow/dags/test.py
[2025-01-21T18:08:47.228+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T18:08:47.234+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:08:47.233+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T18:08:47.618+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:08:47.616+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T18:08:47.623+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T18:08:47.682+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:08:47.682+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T18:08:47.714+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:08:47.714+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T18:08:47.771+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.557 seconds
[2025-01-21T18:09:17.957+0000] {processor.py:186} INFO - Started process (PID=923) to work on /opt/airflow/dags/test.py
[2025-01-21T18:09:17.958+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T18:09:17.960+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:09:17.960+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T18:09:18.109+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:09:18.108+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T18:09:18.111+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T18:09:18.134+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:09:18.134+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T18:09:18.149+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:09:18.148+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T18:09:18.188+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.237 seconds
[2025-01-21T18:09:48.286+0000] {processor.py:186} INFO - Started process (PID=934) to work on /opt/airflow/dags/test.py
[2025-01-21T18:09:48.288+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T18:09:48.289+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:09:48.289+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T18:09:48.440+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:09:48.439+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T18:09:48.442+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T18:09:48.465+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:09:48.465+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T18:09:48.478+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:09:48.478+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T18:09:48.508+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.227 seconds
[2025-01-21T18:10:18.709+0000] {processor.py:186} INFO - Started process (PID=945) to work on /opt/airflow/dags/test.py
[2025-01-21T18:10:18.710+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T18:10:18.712+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:10:18.712+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T18:10:18.872+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:10:18.871+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T18:10:18.874+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T18:10:18.897+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:10:18.897+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T18:10:18.909+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:10:18.908+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T18:10:18.949+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.245 seconds
[2025-01-21T18:10:49.232+0000] {processor.py:186} INFO - Started process (PID=956) to work on /opt/airflow/dags/test.py
[2025-01-21T18:10:49.234+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T18:10:49.236+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:10:49.235+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T18:10:49.399+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:10:49.397+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T18:10:49.401+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T18:10:49.431+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:10:49.431+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T18:10:49.450+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:10:49.449+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T18:10:49.488+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.261 seconds
[2025-01-21T18:11:19.780+0000] {processor.py:186} INFO - Started process (PID=967) to work on /opt/airflow/dags/test.py
[2025-01-21T18:11:19.782+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T18:11:19.784+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:11:19.784+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T18:11:20.002+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:11:20.002+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T18:11:20.005+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T18:11:20.035+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:11:20.034+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T18:11:20.051+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:11:20.050+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T18:11:20.076+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.301 seconds
[2025-01-21T18:11:50.321+0000] {processor.py:186} INFO - Started process (PID=978) to work on /opt/airflow/dags/test.py
[2025-01-21T18:11:50.322+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T18:11:50.324+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:11:50.324+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T18:11:50.480+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:11:50.479+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T18:11:50.482+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T18:11:50.510+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:11:50.510+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T18:11:50.527+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:11:50.526+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T18:11:50.579+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.264 seconds
[2025-01-21T18:12:20.842+0000] {processor.py:186} INFO - Started process (PID=989) to work on /opt/airflow/dags/test.py
[2025-01-21T18:12:20.843+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T18:12:20.849+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:12:20.848+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T18:12:21.077+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:12:21.076+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T18:12:21.079+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T18:12:21.106+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:12:21.106+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T18:12:21.121+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:12:21.121+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T18:12:21.161+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.325 seconds
[2025-01-21T18:12:51.789+0000] {processor.py:186} INFO - Started process (PID=1000) to work on /opt/airflow/dags/test.py
[2025-01-21T18:12:51.790+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T18:12:51.793+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:12:51.792+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T18:12:51.948+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:12:51.947+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T18:12:51.950+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T18:12:51.985+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:12:51.985+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T18:12:52.001+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:12:52.001+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T18:12:52.031+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.247 seconds
[2025-01-21T18:13:22.285+0000] {processor.py:186} INFO - Started process (PID=1011) to work on /opt/airflow/dags/test.py
[2025-01-21T18:13:22.287+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T18:13:22.292+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:13:22.291+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T18:13:22.491+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:13:22.490+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T18:13:22.494+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T18:13:22.519+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:13:22.519+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T18:13:22.534+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:13:22.533+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T18:13:22.555+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.275 seconds
[2025-01-21T18:13:53.161+0000] {processor.py:186} INFO - Started process (PID=1022) to work on /opt/airflow/dags/test.py
[2025-01-21T18:13:53.162+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T18:13:53.164+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:13:53.164+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T18:13:53.319+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:13:53.318+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T18:13:53.321+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T18:13:53.345+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:13:53.345+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T18:13:53.369+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:13:53.368+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T18:13:53.404+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.249 seconds
[2025-01-21T18:14:23.741+0000] {processor.py:186} INFO - Started process (PID=1033) to work on /opt/airflow/dags/test.py
[2025-01-21T18:14:23.743+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T18:14:23.748+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:14:23.747+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T18:14:23.939+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:14:23.938+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T18:14:23.941+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T18:14:23.965+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:14:23.964+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T18:14:23.978+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:14:23.977+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T18:14:23.999+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.263 seconds
[2025-01-21T18:14:54.643+0000] {processor.py:186} INFO - Started process (PID=1044) to work on /opt/airflow/dags/test.py
[2025-01-21T18:14:54.644+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T18:14:54.646+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:14:54.646+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T18:14:54.808+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:14:54.807+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T18:14:54.810+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T18:14:54.833+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:14:54.833+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T18:14:54.847+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:14:54.847+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T18:14:54.887+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.250 seconds
[2025-01-21T18:15:25.032+0000] {processor.py:186} INFO - Started process (PID=1055) to work on /opt/airflow/dags/test.py
[2025-01-21T18:15:25.034+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T18:15:25.038+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:15:25.037+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T18:15:25.249+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:15:25.248+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T18:15:25.252+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T18:15:25.292+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:15:25.292+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T18:15:25.314+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:15:25.314+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T18:15:25.347+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.322 seconds
[2025-01-21T18:15:55.714+0000] {processor.py:186} INFO - Started process (PID=1066) to work on /opt/airflow/dags/test.py
[2025-01-21T18:15:55.715+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T18:15:55.719+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:15:55.718+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T18:15:55.914+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:15:55.913+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T18:15:55.917+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T18:15:55.947+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:15:55.946+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T18:15:55.974+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:15:55.974+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T18:15:56.018+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.310 seconds
[2025-01-21T18:16:26.174+0000] {processor.py:186} INFO - Started process (PID=1077) to work on /opt/airflow/dags/test.py
[2025-01-21T18:16:26.177+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T18:16:26.182+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:16:26.182+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T18:16:26.374+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:16:26.373+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T18:16:26.376+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T18:16:26.403+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:16:26.402+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T18:16:26.416+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:16:26.416+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T18:16:26.438+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.271 seconds
[2025-01-21T18:16:56.698+0000] {processor.py:186} INFO - Started process (PID=1088) to work on /opt/airflow/dags/test.py
[2025-01-21T18:16:56.699+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T18:16:56.701+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:16:56.701+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T18:16:56.849+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:16:56.849+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T18:16:56.852+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T18:16:56.878+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:16:56.877+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T18:16:56.889+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:16:56.889+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T18:16:56.924+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.231 seconds
[2025-01-21T18:17:27.041+0000] {processor.py:186} INFO - Started process (PID=1099) to work on /opt/airflow/dags/test.py
[2025-01-21T18:17:27.042+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T18:17:27.044+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:17:27.044+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T18:17:27.205+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:17:27.204+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T18:17:27.207+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T18:17:27.230+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:17:27.230+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T18:17:27.242+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:17:27.241+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T18:17:27.277+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.241 seconds
[2025-01-21T18:17:57.364+0000] {processor.py:186} INFO - Started process (PID=1110) to work on /opt/airflow/dags/test.py
[2025-01-21T18:17:57.365+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T18:17:57.368+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:17:57.367+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T18:17:57.518+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:17:57.517+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T18:17:57.520+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T18:17:57.543+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:17:57.542+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T18:17:57.555+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:17:57.555+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T18:17:57.589+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.230 seconds
[2025-01-21T18:18:27.724+0000] {processor.py:186} INFO - Started process (PID=1121) to work on /opt/airflow/dags/test.py
[2025-01-21T18:18:27.725+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T18:18:27.727+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:18:27.727+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T18:18:27.877+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:18:27.876+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T18:18:27.880+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T18:18:27.905+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:18:27.904+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T18:18:27.919+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:18:27.919+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T18:18:27.941+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.222 seconds
[2025-01-21T18:18:58.085+0000] {processor.py:186} INFO - Started process (PID=1132) to work on /opt/airflow/dags/test.py
[2025-01-21T18:18:58.086+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-21T18:18:58.089+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:18:58.089+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-21T18:18:58.249+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:18:58.249+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-21T18:18:58.252+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-21T18:18:58.274+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:18:58.273+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-21T18:18:58.287+0000] {logging_mixin.py:190} INFO - [2025-01-21T18:18:58.287+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-21T18:18:58.309+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.229 seconds
