[2025-01-09T18:32:12.764+0000] {processor.py:186} INFO - Started process (PID=89) to work on /opt/airflow/dags/test.py
[2025-01-09T18:32:12.770+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T18:32:12.783+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:32:12.781+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T18:32:13.622+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:32:13.618+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T18:32:13.636+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T18:32:13.751+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:32:13.750+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T18:32:13.872+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:32:13.869+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T18:32:13.960+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 1.235 seconds
[2025-01-09T18:32:44.185+0000] {processor.py:186} INFO - Started process (PID=100) to work on /opt/airflow/dags/test.py
[2025-01-09T18:32:44.186+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T18:32:44.189+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:32:44.189+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T18:32:44.407+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:32:44.406+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T18:32:44.413+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T18:32:44.454+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:32:44.453+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T18:32:44.472+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:32:44.472+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T18:32:44.520+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.342 seconds
[2025-01-09T18:33:14.671+0000] {processor.py:186} INFO - Started process (PID=111) to work on /opt/airflow/dags/test.py
[2025-01-09T18:33:14.672+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T18:33:14.674+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:33:14.674+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T18:33:14.827+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:33:14.826+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T18:33:14.830+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T18:33:14.854+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:33:14.853+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T18:33:14.866+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:33:14.866+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T18:33:14.894+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.228 seconds
[2025-01-09T18:33:45.389+0000] {processor.py:186} INFO - Started process (PID=122) to work on /opt/airflow/dags/test.py
[2025-01-09T18:33:45.399+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T18:33:45.457+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:33:45.455+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T18:33:46.459+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:33:46.456+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T18:33:46.466+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T18:33:46.545+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:33:46.545+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T18:33:46.596+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:33:46.595+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T18:33:46.662+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 1.378 seconds
[2025-01-09T18:34:17.330+0000] {processor.py:186} INFO - Started process (PID=133) to work on /opt/airflow/dags/test.py
[2025-01-09T18:34:17.331+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T18:34:17.335+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:34:17.334+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T18:34:17.525+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:34:17.523+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T18:34:17.529+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T18:34:17.573+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:34:17.573+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T18:34:17.591+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:34:17.591+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T18:34:17.619+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.294 seconds
[2025-01-09T18:34:47.885+0000] {processor.py:186} INFO - Started process (PID=144) to work on /opt/airflow/dags/test.py
[2025-01-09T18:34:47.886+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T18:34:47.889+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:34:47.888+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T18:34:48.084+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:34:48.083+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T18:34:48.087+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T18:34:48.111+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:34:48.111+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T18:34:48.125+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:34:48.125+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T18:34:48.338+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.459 seconds
[2025-01-09T18:35:18.488+0000] {processor.py:186} INFO - Started process (PID=155) to work on /opt/airflow/dags/test.py
[2025-01-09T18:35:18.489+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T18:35:18.491+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:35:18.491+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T18:35:18.669+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:35:18.667+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T18:35:18.672+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T18:35:18.700+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:35:18.700+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T18:35:18.873+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:35:18.873+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T18:35:18.893+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.413 seconds
[2025-01-09T18:35:49.141+0000] {processor.py:186} INFO - Started process (PID=165) to work on /opt/airflow/dags/test.py
[2025-01-09T18:35:49.143+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T18:35:49.148+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:35:49.147+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T18:35:49.405+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:35:49.404+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T18:35:49.409+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T18:35:49.662+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:35:49.662+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T18:35:49.681+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:35:49.681+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T18:35:49.729+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.597 seconds
[2025-01-09T18:36:20.109+0000] {processor.py:186} INFO - Started process (PID=176) to work on /opt/airflow/dags/test.py
[2025-01-09T18:36:20.111+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T18:36:20.114+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:36:20.114+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T18:36:20.360+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:36:20.359+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T18:36:20.364+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T18:36:20.910+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:36:20.910+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T18:36:20.940+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:36:20.940+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T18:36:20.991+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.889 seconds
[2025-01-09T18:36:51.195+0000] {processor.py:186} INFO - Started process (PID=187) to work on /opt/airflow/dags/test.py
[2025-01-09T18:36:51.197+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T18:36:51.200+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:36:51.200+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T18:36:51.556+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:36:51.555+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T18:36:51.559+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T18:36:51.584+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:36:51.584+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T18:36:51.600+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:36:51.600+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T18:36:51.623+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.436 seconds
[2025-01-09T18:37:21.947+0000] {processor.py:186} INFO - Started process (PID=198) to work on /opt/airflow/dags/test.py
[2025-01-09T18:37:21.948+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T18:37:21.953+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:37:21.952+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T18:37:22.456+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:37:22.453+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T18:37:22.465+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T18:37:22.564+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:37:22.564+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T18:37:22.609+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:37:22.608+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T18:37:22.659+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.723 seconds
[2025-01-09T18:37:53.102+0000] {processor.py:186} INFO - Started process (PID=209) to work on /opt/airflow/dags/test.py
[2025-01-09T18:37:53.103+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T18:37:53.105+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:37:53.105+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T18:37:53.271+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:37:53.269+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T18:37:53.273+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T18:37:53.298+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:37:53.298+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T18:37:53.314+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:37:53.313+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T18:37:53.342+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.247 seconds
[2025-01-09T18:38:23.539+0000] {processor.py:186} INFO - Started process (PID=220) to work on /opt/airflow/dags/test.py
[2025-01-09T18:38:23.542+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T18:38:23.546+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:38:23.545+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T18:38:23.737+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:38:23.736+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T18:38:23.740+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T18:38:23.767+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:38:23.767+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T18:38:23.782+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:38:23.781+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T18:38:23.803+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.272 seconds
[2025-01-09T18:38:54.054+0000] {processor.py:186} INFO - Started process (PID=231) to work on /opt/airflow/dags/test.py
[2025-01-09T18:38:54.055+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T18:38:54.058+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:38:54.057+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T18:38:54.222+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:38:54.220+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T18:38:54.225+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T18:38:54.251+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:38:54.251+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T18:38:54.267+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:38:54.267+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T18:38:54.327+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.280 seconds
[2025-01-09T18:39:24.430+0000] {processor.py:186} INFO - Started process (PID=242) to work on /opt/airflow/dags/test.py
[2025-01-09T18:39:24.431+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T18:39:24.434+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:39:24.433+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T18:39:24.599+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:39:24.598+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T18:39:24.602+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T18:39:24.632+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:39:24.631+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T18:39:24.649+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:39:24.648+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T18:39:24.702+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.279 seconds
[2025-01-09T18:39:55.380+0000] {processor.py:186} INFO - Started process (PID=261) to work on /opt/airflow/dags/test.py
[2025-01-09T18:39:55.384+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T18:39:55.400+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:39:55.396+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T18:39:56.449+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:39:56.441+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T18:39:56.460+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T18:39:56.559+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:39:56.559+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T18:39:56.621+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:39:56.620+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T18:39:56.701+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 1.354 seconds
[2025-01-09T18:40:27.030+0000] {processor.py:186} INFO - Started process (PID=272) to work on /opt/airflow/dags/test.py
[2025-01-09T18:40:27.032+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T18:40:27.035+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:40:27.035+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T18:40:27.233+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:40:27.231+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T18:40:27.236+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T18:40:27.270+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:40:27.270+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T18:40:27.298+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:40:27.298+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T18:40:27.345+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.321 seconds
[2025-01-09T18:40:58.285+0000] {processor.py:186} INFO - Started process (PID=283) to work on /opt/airflow/dags/test.py
[2025-01-09T18:40:58.292+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T18:40:58.312+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:40:58.311+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T18:40:59.119+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:40:59.107+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T18:40:59.132+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T18:40:59.233+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:40:59.233+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T18:40:59.282+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:40:59.280+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T18:40:59.351+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 1.112 seconds
[2025-01-09T18:41:29.720+0000] {processor.py:186} INFO - Started process (PID=294) to work on /opt/airflow/dags/test.py
[2025-01-09T18:41:29.721+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T18:41:29.724+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:41:29.723+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T18:41:29.969+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:41:29.968+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T18:41:29.973+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T18:41:30.033+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:41:30.033+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T18:41:30.059+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:41:30.058+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T18:41:30.127+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.415 seconds
[2025-01-09T18:42:00.584+0000] {processor.py:186} INFO - Started process (PID=305) to work on /opt/airflow/dags/test.py
[2025-01-09T18:42:00.585+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T18:42:00.587+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:42:00.587+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T18:42:00.776+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:42:00.775+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T18:42:00.779+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T18:42:00.805+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:42:00.805+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T18:42:00.823+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:42:00.822+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T18:42:00.862+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.286 seconds
[2025-01-09T18:42:31.319+0000] {processor.py:186} INFO - Started process (PID=318) to work on /opt/airflow/dags/test.py
[2025-01-09T18:42:31.321+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T18:42:31.326+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:42:31.325+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T18:42:31.692+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:42:31.688+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T18:42:31.704+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T18:42:31.796+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:42:31.795+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T18:42:31.853+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:42:31.852+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T18:42:31.928+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.616 seconds
[2025-01-09T18:43:02.078+0000] {processor.py:186} INFO - Started process (PID=330) to work on /opt/airflow/dags/test.py
[2025-01-09T18:43:02.079+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T18:43:02.084+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:43:02.083+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T18:43:02.350+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:43:02.349+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T18:43:02.354+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T18:43:02.405+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:43:02.405+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T18:43:02.431+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:43:02.431+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T18:43:02.463+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.394 seconds
[2025-01-09T18:43:33.143+0000] {processor.py:186} INFO - Started process (PID=340) to work on /opt/airflow/dags/test.py
[2025-01-09T18:43:33.145+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T18:43:33.149+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:43:33.149+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T18:43:33.521+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:43:33.518+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T18:43:33.528+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T18:43:33.628+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:43:33.628+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T18:43:33.687+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:43:33.686+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T18:43:33.796+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.664 seconds
[2025-01-09T18:44:04.088+0000] {processor.py:186} INFO - Started process (PID=353) to work on /opt/airflow/dags/test.py
[2025-01-09T18:44:04.090+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T18:44:04.094+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:44:04.093+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T18:44:04.399+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:44:04.396+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T18:44:04.403+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T18:44:04.479+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:44:04.478+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T18:44:04.517+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:44:04.516+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T18:44:04.571+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.494 seconds
[2025-01-09T18:44:35.157+0000] {processor.py:186} INFO - Started process (PID=368) to work on /opt/airflow/dags/test.py
[2025-01-09T18:44:35.159+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T18:44:35.163+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:44:35.163+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T18:44:35.448+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:44:35.447+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T18:44:35.452+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T18:44:35.501+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:44:35.500+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T18:44:35.553+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:44:35.552+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T18:44:35.631+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.486 seconds
[2025-01-09T18:45:06.056+0000] {processor.py:186} INFO - Started process (PID=379) to work on /opt/airflow/dags/test.py
[2025-01-09T18:45:06.057+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T18:45:06.060+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:45:06.059+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T18:45:06.401+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:45:06.399+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T18:45:06.405+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T18:45:06.465+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:45:06.465+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T18:45:06.490+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:45:06.489+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T18:45:06.529+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.488 seconds
[2025-01-09T18:45:37.298+0000] {processor.py:186} INFO - Started process (PID=390) to work on /opt/airflow/dags/test.py
[2025-01-09T18:45:37.300+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T18:45:37.303+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:45:37.302+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T18:45:37.680+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:45:37.678+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T18:45:37.689+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T18:45:37.777+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:45:37.776+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T18:45:37.847+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:45:37.846+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T18:45:37.920+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.631 seconds
[2025-01-09T18:46:08.287+0000] {processor.py:186} INFO - Started process (PID=407) to work on /opt/airflow/dags/test.py
[2025-01-09T18:46:08.289+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T18:46:08.292+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:46:08.291+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T18:46:08.579+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:46:08.575+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T18:46:08.584+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T18:46:08.626+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:46:08.624+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T18:46:08.654+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:46:08.654+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T18:46:08.711+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.431 seconds
[2025-01-09T18:46:38.809+0000] {processor.py:186} INFO - Started process (PID=418) to work on /opt/airflow/dags/test.py
[2025-01-09T18:46:38.811+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T18:46:38.818+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:46:38.817+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T18:46:39.133+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:46:39.131+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T18:46:39.139+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T18:46:39.209+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:46:39.209+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T18:46:39.252+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:46:39.252+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T18:46:39.325+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.526 seconds
[2025-01-09T18:47:09.479+0000] {processor.py:186} INFO - Started process (PID=429) to work on /opt/airflow/dags/test.py
[2025-01-09T18:47:09.481+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T18:47:09.483+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:47:09.482+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T18:47:09.959+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:47:09.955+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T18:47:09.967+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T18:47:10.058+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:47:10.057+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T18:47:10.118+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:47:10.117+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T18:47:10.204+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.738 seconds
[2025-01-09T18:47:41.288+0000] {processor.py:186} INFO - Started process (PID=440) to work on /opt/airflow/dags/test.py
[2025-01-09T18:47:41.291+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T18:47:41.295+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:47:41.294+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T18:47:41.656+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:47:41.655+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T18:47:41.662+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T18:47:41.715+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:47:41.715+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T18:47:41.747+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:47:41.747+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T18:47:41.794+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.521 seconds
[2025-01-09T18:48:12.360+0000] {processor.py:186} INFO - Started process (PID=451) to work on /opt/airflow/dags/test.py
[2025-01-09T18:48:12.361+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T18:48:12.368+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:48:12.368+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T18:48:12.541+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:48:12.540+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T18:48:12.544+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T18:48:12.567+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:48:12.567+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T18:48:12.583+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:48:12.582+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T18:48:12.605+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.252 seconds
[2025-01-09T18:48:42.776+0000] {processor.py:186} INFO - Started process (PID=462) to work on /opt/airflow/dags/test.py
[2025-01-09T18:48:42.777+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T18:48:42.779+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:48:42.779+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T18:48:43.067+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:48:43.065+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T18:48:43.072+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T18:48:43.118+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:48:43.117+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T18:48:43.140+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:48:43.139+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T18:48:43.170+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.403 seconds
[2025-01-09T18:49:13.773+0000] {processor.py:186} INFO - Started process (PID=473) to work on /opt/airflow/dags/test.py
[2025-01-09T18:49:13.774+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T18:49:13.776+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:49:13.776+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T18:49:13.940+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:49:13.940+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T18:49:13.943+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T18:49:13.970+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:49:13.970+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T18:49:13.985+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:49:13.985+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T18:49:14.022+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.259 seconds
[2025-01-09T18:49:44.419+0000] {processor.py:186} INFO - Started process (PID=484) to work on /opt/airflow/dags/test.py
[2025-01-09T18:49:44.422+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T18:49:44.425+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:49:44.424+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T18:49:44.828+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:49:44.826+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T18:49:44.832+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T18:49:44.877+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:49:44.877+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T18:49:44.906+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:49:44.906+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T18:49:44.965+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.560 seconds
[2025-01-09T18:50:15.093+0000] {processor.py:186} INFO - Started process (PID=495) to work on /opt/airflow/dags/test.py
[2025-01-09T18:50:15.095+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T18:50:15.098+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:50:15.097+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T18:50:15.387+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:50:15.386+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T18:50:15.391+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T18:50:15.433+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:50:15.433+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T18:50:15.454+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:50:15.453+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T18:50:15.498+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.417 seconds
[2025-01-09T18:50:45.846+0000] {processor.py:186} INFO - Started process (PID=506) to work on /opt/airflow/dags/test.py
[2025-01-09T18:50:45.847+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T18:50:45.849+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:50:45.848+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T18:50:46.038+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:50:46.037+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T18:50:46.043+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T18:50:46.076+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:50:46.076+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T18:50:46.096+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:50:46.095+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T18:50:46.139+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.301 seconds
[2025-01-09T18:51:16.537+0000] {processor.py:186} INFO - Started process (PID=517) to work on /opt/airflow/dags/test.py
[2025-01-09T18:51:16.544+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T18:51:16.555+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:51:16.550+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T18:51:17.058+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:51:17.055+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T18:51:17.065+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T18:51:17.133+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:51:17.132+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T18:51:17.178+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:51:17.178+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T18:51:17.253+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.762 seconds
[2025-01-09T18:51:48.042+0000] {processor.py:186} INFO - Started process (PID=528) to work on /opt/airflow/dags/test.py
[2025-01-09T18:51:48.044+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T18:51:48.048+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:51:48.047+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T18:51:48.360+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:51:48.358+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T18:51:48.367+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T18:51:48.425+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:51:48.424+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T18:51:48.453+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:51:48.453+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T18:51:48.505+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.474 seconds
[2025-01-09T18:52:18.604+0000] {processor.py:186} INFO - Started process (PID=539) to work on /opt/airflow/dags/test.py
[2025-01-09T18:52:18.605+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T18:52:18.610+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:52:18.609+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T18:52:18.917+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:52:18.915+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T18:52:18.924+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T18:52:18.970+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:52:18.970+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T18:52:19.005+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:52:19.004+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T18:52:19.072+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.480 seconds
[2025-01-09T18:52:49.332+0000] {processor.py:186} INFO - Started process (PID=550) to work on /opt/airflow/dags/test.py
[2025-01-09T18:52:49.333+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T18:52:49.334+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:52:49.334+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T18:52:49.517+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:52:49.516+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T18:52:49.519+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T18:52:49.553+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:52:49.553+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T18:52:49.570+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:52:49.570+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T18:52:49.600+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.278 seconds
[2025-01-09T18:53:19.987+0000] {processor.py:186} INFO - Started process (PID=561) to work on /opt/airflow/dags/test.py
[2025-01-09T18:53:19.991+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T18:53:20.005+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:53:20.003+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T18:53:20.644+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:53:20.642+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T18:53:20.654+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T18:53:20.775+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:53:20.773+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T18:53:20.845+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:53:20.844+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T18:53:20.982+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 1.026 seconds
[2025-01-09T18:53:51.620+0000] {processor.py:186} INFO - Started process (PID=572) to work on /opt/airflow/dags/test.py
[2025-01-09T18:53:51.622+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T18:53:51.626+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:53:51.625+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T18:53:52.056+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:53:52.054+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T18:53:52.068+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T18:53:52.166+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:53:52.165+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T18:53:52.215+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:53:52.214+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T18:53:52.272+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.665 seconds
[2025-01-09T18:54:22.497+0000] {processor.py:186} INFO - Started process (PID=582) to work on /opt/airflow/dags/test.py
[2025-01-09T18:54:22.499+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T18:54:22.501+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:54:22.500+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T18:54:22.740+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:54:22.739+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T18:54:22.744+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T18:54:22.795+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:54:22.794+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T18:54:22.827+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:54:22.827+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T18:54:22.882+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.393 seconds
[2025-01-09T18:54:53.217+0000] {processor.py:186} INFO - Started process (PID=593) to work on /opt/airflow/dags/test.py
[2025-01-09T18:54:53.218+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T18:54:53.219+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:54:53.219+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T18:54:53.380+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:54:53.379+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T18:54:53.382+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T18:54:53.416+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:54:53.415+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T18:54:53.431+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:54:53.431+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T18:54:53.467+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.256 seconds
[2025-01-09T18:55:23.986+0000] {processor.py:186} INFO - Started process (PID=604) to work on /opt/airflow/dags/test.py
[2025-01-09T18:55:23.989+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T18:55:23.992+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:55:23.991+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T18:55:24.370+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:55:24.368+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T18:55:24.375+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T18:55:24.428+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:55:24.427+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T18:55:24.460+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:55:24.459+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T18:55:24.515+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.546 seconds
[2025-01-09T18:55:54.675+0000] {processor.py:186} INFO - Started process (PID=615) to work on /opt/airflow/dags/test.py
[2025-01-09T18:55:54.676+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T18:55:54.678+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:55:54.678+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T18:55:54.922+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:55:54.921+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T18:55:54.926+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T18:55:54.965+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:55:54.964+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T18:55:54.987+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:55:54.986+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T18:55:55.032+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.366 seconds
[2025-01-09T18:56:25.303+0000] {processor.py:186} INFO - Started process (PID=626) to work on /opt/airflow/dags/test.py
[2025-01-09T18:56:25.305+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T18:56:25.307+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:56:25.307+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T18:56:25.574+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:56:25.573+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T18:56:25.577+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T18:56:25.602+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:56:25.602+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T18:56:25.618+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:56:25.617+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T18:56:25.644+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.350 seconds
[2025-01-09T18:56:55.876+0000] {processor.py:186} INFO - Started process (PID=637) to work on /opt/airflow/dags/test.py
[2025-01-09T18:56:55.877+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T18:56:55.879+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:56:55.878+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T18:56:56.067+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:56:56.066+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T18:56:56.070+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T18:56:56.104+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:56:56.103+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T18:56:56.120+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:56:56.119+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T18:56:56.163+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.294 seconds
[2025-01-09T18:57:26.435+0000] {processor.py:186} INFO - Started process (PID=648) to work on /opt/airflow/dags/test.py
[2025-01-09T18:57:26.436+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T18:57:26.439+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:57:26.438+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T18:57:26.678+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:57:26.677+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T18:57:26.682+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T18:57:26.716+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:57:26.715+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T18:57:26.736+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:57:26.736+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T18:57:26.771+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.349 seconds
[2025-01-09T18:57:57.511+0000] {processor.py:186} INFO - Started process (PID=659) to work on /opt/airflow/dags/test.py
[2025-01-09T18:57:57.514+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T18:57:57.516+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:57:57.516+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T18:57:57.735+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:57:57.733+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T18:57:57.739+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T18:57:57.770+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:57:57.770+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T18:57:57.788+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:57:57.788+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T18:57:57.819+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.317 seconds
[2025-01-09T18:58:28.422+0000] {processor.py:186} INFO - Started process (PID=670) to work on /opt/airflow/dags/test.py
[2025-01-09T18:58:28.424+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T18:58:28.428+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:58:28.426+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T18:58:28.995+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:58:28.989+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T18:58:29.004+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T18:58:29.111+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:58:29.110+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T18:58:29.196+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:58:29.195+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T18:58:29.292+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.880 seconds
[2025-01-09T18:58:59.739+0000] {processor.py:186} INFO - Started process (PID=693) to work on /opt/airflow/dags/test.py
[2025-01-09T18:58:59.740+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T18:58:59.744+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:58:59.743+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T18:58:59.988+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:58:59.987+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T18:58:59.992+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T18:59:00.034+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:59:00.034+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T18:59:00.060+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:59:00.059+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T18:59:00.088+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.358 seconds
[2025-01-09T18:59:30.638+0000] {processor.py:186} INFO - Started process (PID=706) to work on /opt/airflow/dags/test.py
[2025-01-09T18:59:30.640+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T18:59:30.642+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:59:30.642+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T18:59:30.853+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:59:30.852+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T18:59:30.857+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T18:59:30.892+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:59:30.892+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T18:59:30.916+0000] {logging_mixin.py:190} INFO - [2025-01-09T18:59:30.916+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T18:59:30.943+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.318 seconds
[2025-01-09T19:00:01.696+0000] {processor.py:186} INFO - Started process (PID=720) to work on /opt/airflow/dags/test.py
[2025-01-09T19:00:01.698+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T19:00:01.701+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:00:01.699+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T19:00:01.942+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:00:01.940+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T19:00:01.947+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T19:00:01.985+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:00:01.984+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T19:00:02.007+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:00:02.007+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T19:00:02.053+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.368 seconds
[2025-01-09T19:00:32.455+0000] {processor.py:186} INFO - Started process (PID=730) to work on /opt/airflow/dags/test.py
[2025-01-09T19:00:32.458+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T19:00:32.460+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:00:32.460+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T19:00:32.719+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:00:32.717+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T19:00:32.723+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T19:00:32.767+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:00:32.767+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T19:00:32.791+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:00:32.791+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T19:00:32.825+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.382 seconds
[2025-01-09T19:01:03.375+0000] {processor.py:186} INFO - Started process (PID=740) to work on /opt/airflow/dags/test.py
[2025-01-09T19:01:03.376+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T19:01:03.378+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:01:03.377+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T19:01:03.555+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:01:03.554+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T19:01:03.559+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T19:01:03.591+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:01:03.590+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T19:01:03.607+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:01:03.607+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T19:01:03.655+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.288 seconds
[2025-01-09T19:01:34.234+0000] {processor.py:186} INFO - Started process (PID=750) to work on /opt/airflow/dags/test.py
[2025-01-09T19:01:34.236+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T19:01:34.238+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:01:34.238+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T19:01:34.429+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:01:34.428+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T19:01:34.434+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T19:01:34.465+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:01:34.464+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T19:01:34.487+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:01:34.487+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T19:01:34.513+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.288 seconds
[2025-01-09T19:02:05.042+0000] {processor.py:186} INFO - Started process (PID=760) to work on /opt/airflow/dags/test.py
[2025-01-09T19:02:05.043+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T19:02:05.045+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:02:05.044+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T19:02:05.206+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:02:05.205+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T19:02:05.208+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T19:02:05.233+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:02:05.233+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T19:02:05.248+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:02:05.247+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T19:02:05.321+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.286 seconds
[2025-01-09T19:02:35.999+0000] {processor.py:186} INFO - Started process (PID=770) to work on /opt/airflow/dags/test.py
[2025-01-09T19:02:36.001+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T19:02:36.002+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:02:36.002+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T19:02:36.158+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:02:36.157+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T19:02:36.160+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T19:02:36.185+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:02:36.185+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T19:02:36.196+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:02:36.196+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T19:02:36.229+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.237 seconds
[2025-01-09T19:03:06.785+0000] {processor.py:186} INFO - Started process (PID=780) to work on /opt/airflow/dags/test.py
[2025-01-09T19:03:06.786+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T19:03:06.788+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:03:06.788+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T19:03:06.944+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:03:06.943+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T19:03:06.946+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T19:03:06.973+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:03:06.972+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T19:03:06.987+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:03:06.986+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T19:03:07.045+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.267 seconds
[2025-01-09T19:03:37.725+0000] {processor.py:186} INFO - Started process (PID=790) to work on /opt/airflow/dags/test.py
[2025-01-09T19:03:37.726+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T19:03:37.728+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:03:37.727+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T19:03:37.877+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:03:37.876+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T19:03:37.879+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T19:03:37.901+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:03:37.900+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T19:03:37.913+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:03:37.913+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T19:03:37.951+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.233 seconds
[2025-01-09T19:04:08.526+0000] {processor.py:186} INFO - Started process (PID=800) to work on /opt/airflow/dags/test.py
[2025-01-09T19:04:08.527+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T19:04:08.530+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:04:08.529+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T19:04:08.699+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:04:08.698+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T19:04:08.702+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T19:04:08.730+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:04:08.730+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T19:04:08.745+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:04:08.744+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T19:04:08.787+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.267 seconds
[2025-01-09T19:04:39.324+0000] {processor.py:186} INFO - Started process (PID=810) to work on /opt/airflow/dags/test.py
[2025-01-09T19:04:39.326+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T19:04:39.330+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:04:39.329+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T19:04:39.543+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:04:39.542+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T19:04:39.547+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T19:04:39.583+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:04:39.582+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T19:04:39.602+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:04:39.602+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T19:04:39.632+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.316 seconds
[2025-01-09T19:05:10.415+0000] {processor.py:186} INFO - Started process (PID=827) to work on /opt/airflow/dags/test.py
[2025-01-09T19:05:10.417+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T19:05:10.418+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:05:10.418+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T19:05:10.572+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:05:10.572+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T19:05:10.576+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T19:05:10.602+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:05:10.602+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T19:05:10.620+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:05:10.619+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T19:05:10.669+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.261 seconds
[2025-01-09T19:05:40.917+0000] {processor.py:186} INFO - Started process (PID=838) to work on /opt/airflow/dags/test.py
[2025-01-09T19:05:40.919+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T19:05:40.920+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:05:40.920+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T19:05:41.076+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:05:41.076+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T19:05:41.079+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T19:05:41.101+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:05:41.100+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T19:05:41.113+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:05:41.112+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T19:05:41.139+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.228 seconds
[2025-01-09T19:06:11.421+0000] {processor.py:186} INFO - Started process (PID=849) to work on /opt/airflow/dags/test.py
[2025-01-09T19:06:11.423+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T19:06:11.425+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:06:11.424+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T19:06:11.596+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:06:11.595+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T19:06:11.599+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T19:06:11.629+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:06:11.629+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T19:06:11.649+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:06:11.648+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T19:06:11.671+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.257 seconds
[2025-01-09T19:06:41.716+0000] {processor.py:186} INFO - Started process (PID=860) to work on /opt/airflow/dags/test.py
[2025-01-09T19:06:41.718+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T19:06:41.721+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:06:41.720+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T19:06:41.882+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:06:41.881+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T19:06:41.885+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T19:06:41.910+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:06:41.910+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T19:06:41.925+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:06:41.925+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T19:06:41.964+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.258 seconds
[2025-01-09T19:07:12.030+0000] {processor.py:186} INFO - Started process (PID=871) to work on /opt/airflow/dags/test.py
[2025-01-09T19:07:12.032+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T19:07:12.034+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:07:12.033+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T19:07:12.204+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:07:12.203+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T19:07:12.208+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T19:07:12.269+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:07:12.269+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T19:07:12.289+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:07:12.289+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T19:07:12.319+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.297 seconds
[2025-01-09T19:07:43.089+0000] {processor.py:186} INFO - Started process (PID=882) to work on /opt/airflow/dags/test.py
[2025-01-09T19:07:43.091+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T19:07:43.094+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:07:43.093+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T19:07:43.438+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:07:43.435+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T19:07:43.444+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T19:07:43.510+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:07:43.509+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T19:07:43.556+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:07:43.555+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T19:07:43.610+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.533 seconds
[2025-01-09T19:08:13.917+0000] {processor.py:186} INFO - Started process (PID=893) to work on /opt/airflow/dags/test.py
[2025-01-09T19:08:13.924+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T19:08:13.927+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:08:13.926+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T19:08:14.096+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:08:14.095+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T19:08:14.098+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T19:08:14.129+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:08:14.128+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T19:08:14.152+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:08:14.152+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T19:08:14.176+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.267 seconds
[2025-01-09T19:08:44.553+0000] {processor.py:186} INFO - Started process (PID=904) to work on /opt/airflow/dags/test.py
[2025-01-09T19:08:44.554+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T19:08:44.555+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:08:44.555+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T19:08:44.724+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:08:44.722+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T19:08:44.727+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T19:08:44.761+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:08:44.760+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T19:08:44.786+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:08:44.786+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T19:08:44.809+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.264 seconds
[2025-01-09T19:09:14.893+0000] {processor.py:186} INFO - Started process (PID=915) to work on /opt/airflow/dags/test.py
[2025-01-09T19:09:14.894+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T19:09:14.896+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:09:14.896+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T19:09:15.105+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:09:15.104+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T19:09:15.109+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T19:09:15.139+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:09:15.139+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T19:09:15.157+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:09:15.156+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T19:09:15.196+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.310 seconds
[2025-01-09T19:09:45.803+0000] {processor.py:186} INFO - Started process (PID=926) to work on /opt/airflow/dags/test.py
[2025-01-09T19:09:45.804+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T19:09:45.806+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:09:45.806+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T19:09:45.972+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:09:45.971+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T19:09:45.975+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T19:09:46.001+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:09:46.001+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T19:09:46.017+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:09:46.016+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T19:09:46.043+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.247 seconds
[2025-01-09T19:10:16.471+0000] {processor.py:186} INFO - Started process (PID=937) to work on /opt/airflow/dags/test.py
[2025-01-09T19:10:16.473+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T19:10:16.476+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:10:16.476+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T19:10:16.651+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:10:16.650+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T19:10:16.655+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T19:10:16.682+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:10:16.682+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T19:10:16.697+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:10:16.697+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T19:10:16.731+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.269 seconds
[2025-01-09T19:10:46.977+0000] {processor.py:186} INFO - Started process (PID=948) to work on /opt/airflow/dags/test.py
[2025-01-09T19:10:46.979+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T19:10:46.981+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:10:46.981+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T19:10:47.143+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:10:47.142+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T19:10:47.146+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T19:10:47.173+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:10:47.173+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T19:10:47.187+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:10:47.187+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T19:10:47.210+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.243 seconds
[2025-01-09T19:11:17.565+0000] {processor.py:186} INFO - Started process (PID=959) to work on /opt/airflow/dags/test.py
[2025-01-09T19:11:17.566+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/test.py for tasks to queue
[2025-01-09T19:11:17.567+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:11:17.567+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/test.py
[2025-01-09T19:11:17.764+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:11:17.763+0000] {templater.py:94} ERROR - Failed to resolve template field '_sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 92, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 207, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: test.sql
[2025-01-09T19:11:17.767+0000] {processor.py:925} INFO - DAG(s) 'test' retrieved from /opt/airflow/dags/test.py
[2025-01-09T19:11:17.798+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:11:17.797+0000] {dag.py:3239} INFO - Sync 1 DAGs
[2025-01-09T19:11:17.812+0000] {logging_mixin.py:190} INFO - [2025-01-09T19:11:17.812+0000] {dag.py:4180} INFO - Setting next_dagrun for test to None, run_after=None
[2025-01-09T19:11:17.839+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/test.py took 0.281 seconds
